"""
generate_client_seed.py
Generates dummy public.client data -- simulates the external CRM/core-banking
system this pipeline is based on but doesn't own. Run manually, not part of
the DAG (this represents a system we don't control).

Samples ~60% phone-number overlap from the synthetic source workbook
(data/source/CUSTOMER_SUPPORT-2025.xlsx, itself generated by
generate_synthetic_source.py) -- both sides are fully synthetic.

Run generate_synthetic_source.py first if data/source/ doesn't exist yet.

Outputs sql/init/01_seed_client.sql for local Docker init.
"""

import random
import pandas as pd

random.seed(42)  # reproducible

VALID_REGIONS = [
    "Ashanti Region", "Greater Accra Region", "Northern Region", "Volta Region",
    "Central Region", "Western Region", "Upper West Region", "Upper East Region",
    "Oti Region", "Savannah Region", "Bono East Region", "Western North Region",
    "Brong Ahafo Region", "North East Region", "Ahafo Region", "Eastern Region",
]
GENDERS = ["Male", "Female", "Other"]

SOURCE_EXCEL = "data/source/CUSTOMER_SUPPORT-2025.xlsx"
TOTAL_CLIENTS = 1000
OVERLAP_FRACTION = 0.6
NUMBER2_FRACTION = 0.15

AKAN_DAY_NAMES_MALE = ["Kwasi", "Kwadwo", "Kwabena", "Kwaku", "Yaw", "Kofi", "Kwame"]
AKAN_DAY_NAMES_FEMALE = ["Akosua", "Adwoa", "Abena", "Akua", "Yaa", "Afua", "Ama"]

GHANAIAN_FIRST_MALE = [
    "Kwame", "Kofi", "Kwabena", "Yaw", "Kwesi", "Kwaku", "Nana", "Kojo",
    "Fiifi", "Ebo", "Kobina", "Nii", "Tetteh", "Emmanuel", "Samuel", "Daniel",
    "Prince", "Isaac", "Michael", "Nicholas",
    "Mawuli", "Elikem", "Selorm", "Dela", "Kudzo",
    "Yakubu", "Iddrisu", "Musah", "Sulemana", "Alhassan", "Mumuni",
]
GHANAIAN_FIRST_FEMALE = [
    "Abena", "Akua", "Ama", "Akosua", "Efua", "Yaa", "Adjoa", "Afia",
    "Naa", "Korkor", "Ayele", "Efe",
    "Adwoa", "Afua", "Comfort", "Priscilla", "Belinda", "Vivian",
    "Mawusi", "Delali", "Sitsofe", "Enam",
    "Aisha", "Fatima", "Zulaikha", "Rukayat", "Hawa",
]
GHANAIAN_SURNAMES = [
    "Mensah", "Owusu", "Boateng", "Asante", "Amoah", "Osei", "Adjei",
    "Agyeman", "Appiah", "Sarpong", "Ofori", "Acheampong", "Antwi",
    "Nkrumah", "Danquah", "Ankrah",
    "Tetteh", "Lartey", "Ashong", "Ablorh", "Adjetey", "Kotey",
    "Amenyo", "Dogbe", "Agbeko", "Gadzekpo",
    "Mahama", "Iddrisu", "Alhassan", "Abdulai", "Fuseini", "Yakubu",
    "Ackah", "Kaku",
]
INTERNATIONAL_FIRST_MALE = ["James", "David", "Michael", "Robert", "John", "Wei", "Ahmed", "Carlos"]
INTERNATIONAL_FIRST_FEMALE = ["Sarah", "Emma", "Grace", "Linda", "Mei", "Fatimah", "Sofia", "Anna"]
INTERNATIONAL_SURNAMES = ["Smith", "Johnson", "Williams", "Chen", "Khan", "Garcia", "Müller", "Kim"]


def generate_name(gender: str) -> str:
    name_gender = gender if gender in ("Male", "Female") else random.choice(["Male", "Female"])
    if random.random() < 0.75:
        if name_gender == "Male":
            first = random.choice(GHANAIAN_FIRST_MALE)
            if random.random() < 0.4:
                first = f"{random.choice(AKAN_DAY_NAMES_MALE)} {first}"
        else:
            first = random.choice(GHANAIAN_FIRST_FEMALE)
            if random.random() < 0.4:
                first = f"{random.choice(AKAN_DAY_NAMES_FEMALE)} {first}"
        surname = random.choice(GHANAIAN_SURNAMES)
    else:
        first = random.choice(INTERNATIONAL_FIRST_MALE if name_gender == "Male" else INTERNATIONAL_FIRST_FEMALE)
        surname = random.choice(INTERNATIONAL_SURNAMES)
    return f"{first} {surname}"


def to_e164(raw: str) -> str:
    digits = "".join(c for c in raw if c.isdigit())
    return "+233" + digits[1:] if digits.startswith("0") else "+233" + digits


def fake_ghana_number(used: set) -> str:
    while True:
        n = f"+233{random.randint(20,59)}{random.randint(1000000,9999999)}"
        if n not in used:
            used.add(n)
            return n


def load_source_numbers() -> list[str]:
    xl = pd.ExcelFile(SOURCE_EXCEL)
    numbers = set()
    for sheet in xl.sheet_names:
        if sheet == "Unresolved":
            continue
        df = xl.parse(sheet)
        if "NUMBER" in df.columns:
            numbers.update(df["NUMBER"].dropna().astype(str).str.strip().tolist())
    return sorted(numbers)


def generate_profile_id(used: set) -> str:
    while True:
        pid = f"{random.randint(0, 999999999):09d}"
        if pid not in used:
            used.add(pid)
            return pid


def generate_clients() -> pd.DataFrame:
    source_numbers = load_source_numbers()
    overlap_sample = random.sample(source_numbers, k=int(len(source_numbers) * OVERLAP_FRACTION))
    overlap_e164 = [to_e164(n) for n in overlap_sample]

    used_numbers = set(overlap_e164)
    used_ids = set()
    rows = []

    for phone in overlap_e164:
        gender = random.choice(GENDERS)
        phone2 = fake_ghana_number(used_numbers) if random.random() < NUMBER2_FRACTION else None
        rows.append({
            "profileId": generate_profile_id(used_ids),
            "accountHolderName": generate_name(gender),
            "gender": gender,
            "phoneNumber": phone,
            "phoneNumber2": phone2,
            "region": random.choice(VALID_REGIONS),
        })

    remaining = TOTAL_CLIENTS - len(rows)
    for _ in range(remaining):
        gender = random.choice(GENDERS)
        phone = fake_ghana_number(used_numbers)
        phone2 = fake_ghana_number(used_numbers) if random.random() < NUMBER2_FRACTION else None
        rows.append({
            "profileId": generate_profile_id(used_ids),
            "accountHolderName": generate_name(gender),
            "gender": gender,
            "phoneNumber": phone,
            "phoneNumber2": phone2,
            "region": random.choice(VALID_REGIONS),
        })

    return pd.DataFrame(rows)


def write_sql(df: pd.DataFrame, path: str):
    lines = []
    for _, r in df.iterrows():
        phone2 = f"'{r['phoneNumber2']}'" if r["phoneNumber2"] else "NULL"
        name = r["accountHolderName"].replace("'", "''")
        lines.append(
            f"('{r['profileId']}', '{name}', '{r['gender']}', "
            f"'{r['phoneNumber']}', {phone2}, '{r['region']}')"
        )
    sql = (
        
        'INSERT INTO public.client ("profileId", "accountHolderName", "gender", '
        '"phoneNumber", "phoneNumber2", "region") VALUES\n'
        + ",\n".join(lines)
        + '\nON CONFLICT ("profileId") DO NOTHING;\n'
    )
    with open(path, "w") as f:
        f.write(sql)


if __name__ == "__main__":
    df = generate_clients()
    write_sql(df, "sql/init/01_seed_client.sql")
    print(f"Generated {len(df)} clients.")
    print(f"  With phoneNumber2: {df['phoneNumber2'].notna().sum()}")
    print("Wrote sql/init/01_seed_client.sql")